name: build
on:
  push:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v1
      with:
        go-version: 1.15.12
    - uses: actions/checkout@v2
    - run: go build ./pkg/beagle
