name: image
on:
  push:
    tags:
    - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # this can be declared without content if there isn't any extra tag:
      # EXTRA_TAGS:
      EXTRA_TAGS: latest canary
    steps:
    - name: Run envvars
      run: |
        GIT_TAG="${GITHUB_REF#refs/tags/}"
        TAGS=$(
          for repository in quay.io/jcmoraisjr jcmoraisjr; do
            for project in beagle; do
              for tag in "$GIT_TAG" ${{ env.EXTRA_TAGS }}; do
                echo -n "${repository}/${project}:${tag},"
              done
            done
          done
        )
        echo "GIT_TAG=$GIT_TAG" >> $GITHUB_ENV
        echo "TAGS=$TAGS" >> $GITHUB_ENV
    - uses: actions/checkout@v2
    - uses: docker/login-action@v1 
      with:
        username: jcmoraisjr
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - uses: docker/login-action@v1 
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_TOKEN }}
    - uses: docker/setup-qemu-action@v1
    - uses: docker/setup-buildx-action@v1
    - uses: docker/build-push-action@v2
      with:
        context: .
        file: builder/Dockerfile
        platforms: linux/amd64,linux/arm64/v8,linux/arm/v7,linux/arm/v6,linux/s390x
        push: true
        build-args: |
          GIT_TAG=${{ env.GIT_TAG }}
        tags: ${{ env.TAGS }}
