name: image
on:
  push:
    tags:
    - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: jcmoraisjr
    steps:
    - uses: actions/checkout@v2
    - uses: docker/login-action@v1 
      with:
        username: ${{ env.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - uses: docker/login-action@v1 
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_TOKEN }}
    - uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-
    - run: |
        echo "GIT_TAG=$(echo $GITHUB_REF | sed -n 's,refs/tags/,,p')" >> $GITHUB_ENV
    - uses: docker/setup-buildx-action@v1
    - uses: docker/build-push-action@v2
      with:
        context: .
        file: builder/Dockerfile
        platforms: linux/amd64
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new
        push: true
        build-args: |
          GIT_TAG=${{ env.GIT_TAG }}
        tags: |
          quay.io/jcmoraisjr/beagle:${{ env.GIT_TAG }}
          jcmoraisjr/beagle:${{ env.GIT_TAG }}
    # Temp fix
    # https://github.com/docker/build-push-action/issues/252
    # https://github.com/moby/buildkit/issues/1896
    # https://github.com/docker/build-push-action/blob/master/docs/advanced/cache.md
    - name: move cache
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache
